[package]
name = "r08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert2 = "0.3.11"
indicatif = "0.17.7"
phf = "0.11.2"
phf_codegen = "0.11.2"
regex = "1.10.2"
